repos:
   -  repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.8.4
      hooks:
         -  id: ruff-format
            args: [ "--config=pyproject.toml" ]
         -  id: ruff
            args: [ "--config=pyproject.toml", "--fix" ]

   -  repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.12.0
      hooks:
         -  id: mypy
            args: [ "--config-file=pyproject.toml" ]
